"""add connections table

Revision ID: 25948f80e4d6
Revises: 70a16fa276f5
Create Date: 2026-07-03 23:48:17.873780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25948f80e4d6'
down_revision: Union[str, Sequence[str], None] = '70a16fa276f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('DUCKDB_FILE', 'SNOWFLAKE', name='connectiontype'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_name'), 'connections', ['name'], unique=True)
    op.create_index(op.f('ix_connections_owner_id'), 'connections', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_owner_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_name'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
